name: Build Android APK

on:
  push:
    branches:
      - main  # запускается при пуше в ветку main
  workflow_dispatch:  # можно запускать вручную из вкладки Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Устанавливаем зависимости системы
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3.10-venv python3.10-dev \
            build-essential git openjdk-11-jdk zlib1g-dev libffi-dev \
            libssl-dev libsqlite3-dev libncurses5-dev unzip

      # 4️⃣ Создаём виртуальное окружение и ставим библиотеки
      - name: Install Python dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install cython buildozer kivy matplotlib numpy

      # 5️⃣ Настраиваем Java
      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
          echo "/usr/lib/jvm/java-11-openjdk-amd64/bin" >> $GITHUB_PATH

      # 6️⃣ Сборка APK
      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      # 7️⃣ Загружаем APK как артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: bin/*.apk
